ALTER TABLE logements ADD COLUMN IF NOT EXISTS nb_modifications INTEGER DEFAULT 0;
ALTER TABLE locataires ADD COLUMN IF NOT EXISTS nb_modifications INTEGER DEFAULT 0;
ALTER TABLE quittances ADD COLUMN IF NOT EXISTS nb_modifications INTEGER DEFAULT 0;
